from ...core.config import settings
from ...core.models import ContentItem
from typing import Optional
import httpx, json, os, logging, base64

logger = logging.getLogger(__name__)


class ConfluenceIntegration:
    def __init__(self, base_url: str = None, api_token: str = None, space_key: str = None):
        self.base_url = (base_url or os.environ.get("CONFLUENCE_BASE_URL", "")).rstrip("/")
        self.api_token = api_token or os.environ.get("CONFLUENCE_API_TOKEN", "")
        self.space_key = space_key or os.environ.get("CONFLUENCE_SPACE_KEY", "")
        self.api_base = f"{self.base_url}/wiki/api/v2"
        auth_str = f"{self.api_token}"
        self._auth_header = f"Basic {base64.b64encode(auth_str.encode()).decode()}"
        self._client = httpx.Client(timeout=30)

    def _headers(self) -> dict:
        return {
            "Authorization": self._auth_header,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _request(self, method: str, path: str, data: dict = None) -> Optional[dict]:
        if not self.base_url or not self.api_token or not self.space_key:
            logger.warning("Confluence not fully configured")
            return None
        url = f"{self.api_base}{path}"
        for attempt in range(3):
            try:
                resp = self._client.request(method, url, headers=self._headers(), json=data)
                if resp.status_code == 401:
                    logger.error("Confluence auth failed - check API token")
                    return {"error": "Authentication failed"}
                if resp.status_code == 404:
                    logger.warning(f"Confluence resource not found: {path}")
                    return None
                resp.raise_for_status()
                return resp.json() if resp.content else {}
            except httpx.HTTPError as e:
                logger.error(f"Confluence request failed: {e}")
                if attempt == 2:
                    return {"error": str(e)}
                import time
                time.sleep(1)
        return {"error": "Max retries exceeded"}

    def _storage_format(self, content: str) -> dict:
        html_content = content.replace("\n", "<br/>")
        return {
            "representation": "storage",
            "value": f"<p>{html_content}</p>",
        }

    def create_page(self, title: str, content: str, parent_id: str = None) -> dict:
        data = {
            "spaceId": self.space_key,
            "title": title,
            "body": self._storage_format(content),
        }
        if parent_id:
            data["parentId"] = parent_id
        result = self._request("POST", "/pages", data)
        return result or {"error": "Failed to create page"}

    def create_digest_page(self, digest_text: str, topic: str = None, labels: list[str] = None) -> dict:
        from datetime import datetime
        topic_suffix = f" - {topic}" if topic else ""
        title = f"AI Content Digest - {datetime.now().strftime('%Y-%m-%d')}{topic_suffix}"
        body_lines = [
            f"h1. AI Content Hub Digest{topic_suffix}",
            f"*Generated: {datetime.now().isoformat()}*",
            "",
            "---",
            "",
            digest_text,
            "",
            "---",
            "",
            "*This digest was automatically generated by AI Content Hub*",
        ]
        body = "\n".join(body_lines)
        result = self.create_page(title, body)
        if result and labels:
            page_id = result.get("id")
            if page_id:
                self._request("PUT", f"/pages/{page_id}/labels", {
                    "labels": [{"prefix": "global", "name": l} for l in labels]
                })
        return result or {"error": "Failed to create digest page"}

    def update_page(self, page_id: str, content: str, title: str = None) -> bool:
        existing = self._request("GET", f"/pages/{page_id}")
        if not existing:
            return False
        version = existing.get("version", {}).get("number", 0)
        data = {
            "id": page_id,
            "version": {"number": version + 1, "message": "Updated by AI Content Hub"},
            "body": self._storage_format(content),
        }
        if title:
            data["title"] = title
        result = self._request("PUT", f"/pages/{page_id}", data)
        return result is not None and "error" not in result

    def search_content(self, query: str, limit: int = 10) -> list[dict]:
        result = self._request("GET", f"/pages?spaceId={self.space_key}&title={query}&limit={limit}")
        pages = []
        if result and "results" in result:
            for p in result["results"]:
                pages.append({
                    "id": p.get("id"),
                    "title": p.get("title"),
                    "space_id": p.get("spaceId"),
                    "version": p.get("version", {}).get("number"),
                    "created_at": p.get("createdAt"),
                    "modified_at": p.get("modifiedAt"),
                    "status": p.get("status"),
                })
        return pages

    def get_page_children(self, page_id: str) -> list[dict]:
        result = self._request("GET", f"/pages/{page_id}/children")
        children = []
        if result and "results" in result:
            for c in result["results"]:
                children.append({
                    "id": c.get("id"),
                    "title": c.get("title"),
                    "space_id": c.get("spaceId"),
                    "version": c.get("version", {}).get("number"),
                    "created_at": c.get("createdAt"),
                    "status": c.get("status"),
                })
        return children
