from ...core.config import settings
from ...core.models import ContentItem, ClassifiedItem
from typing import Optional
import httpx, json, os, logging

logger = logging.getLogger(__name__)

SEVERITY_THEMES = {
    "info": {"color": "light", "accent": "0078D4"},
    "warning": {"color": "warning", "accent": "FF8C00"},
    "error": {"color": "attention", "accent": "E81123"},
    "danger": {"color": "attention", "accent": "E81123"},
    "critical": {"color": "attention", "accent": "D13438"},
    "success": {"color": "good", "accent": "107C10"},
}

SOURCE_BADGES = {
    "linkedin": "LinkedIn", "reddit": "Reddit", "techcrunch": "TechCrunch",
    "techgig": "TechGig", "arxiv": "arXiv", "youtube": "YouTube",
    "hackernews": "Hacker News", "medium": "Medium", "rss": "RSS",
    "newsapi": "NewsAPI", "devto": "DEV.to",
}


class TeamsIntegration:
    def __init__(self, webhook_url: str = None):
        self.webhook_url = webhook_url or getattr(settings, "TEAMS_WEBHOOK_URL", None) or ""
        self._client = httpx.Client(timeout=30)

    def _post(self, payload: dict) -> bool:
        if not self.webhook_url:
            logger.warning("Teams webhook URL not configured")
            return False
        try:
            resp = self._client.post(self.webhook_url, json=payload)
            if resp.status_code == 429:
                logger.warning("Teams rate limited")
                return False
            resp.raise_for_status()
            return True
        except httpx.HTTPError as e:
            logger.error(f"Teams webhook failed: {e}")
            return False

    def send_message(self, text: str, title: str = None) -> bool:
        card = self._build_adaptive_card(
            body=[
                {
                    "type": "TextBlock",
                    "text": title or "Notification",
                    "weight": "bolder",
                    "size": "medium",
                },
                {
                    "type": "TextBlock",
                    "text": text,
                    "wrap": True,
                },
            ]
        )
        return self._post(card)

    def send_content_card(self, item: ContentItem) -> bool:
        snippet = (item.content_cleaned or item.content)[:280]
        source_badge = SOURCE_BADGES.get(item.source, item.source)
        body = []
        if item.image_urls:
            body.append({
                "type": "Image",
                "url": item.image_urls[0],
                "altText": item.title,
                "spacing": "none",
                "height": "auto",
            })
        body.append({
            "type": "TextBlock",
            "text": item.title[:120],
            "weight": "bolder",
            "size": "large",
            "wrap": True,
        })
        body.append({
            "type": "FactSet",
            "facts": [
                {"title": "Source", "value": source_badge},
                {"title": "Score", "value": f"{item.relevance_score:.2f}"},
                {"title": "Engagement", "value": str(item.engagement)},
            ],
        })
        if snippet:
            body.append({
                "type": "TextBlock",
                "text": snippet,
                "wrap": True,
                "maxLines": 4,
            })
        if item.topics:
            topics_str = " \u2022 ".join(item.topics[:6])
            body.append({
                "type": "TextBlock",
                "text": f"**Topics:** {topics_str}",
                "wrap": True,
                "isSubtle": True,
                "size": "small",
            })
        actions = []
        if item.url:
            actions.append({
                "type": "Action.OpenUrl",
                "title": "Open Original",
                "url": item.url,
            })
        actions.append({
            "type": "Action.Submit",
            "title": "Summarize",
            "data": {"action": "summarize", "item_id": item.id},
        })
        card = self._build_adaptive_card(body, actions)
        return self._post(card)

    def send_digest(self, digest_text: str, topic: str = None) -> bool:
        topic_label = f" \u2014 {topic}" if topic else ""
        body = [
            {
                "type": "TextBlock",
                "text": f"Daily Digest{topic_label}",
                "weight": "bolder",
                "size": "extraLarge",
            },
            {"type": "TextBlock", "text": digest_text[:2000], "wrap": True},
            {
                "type": "TextBlock",
                "text": "Generated by AI Content Hub",
                "isSubtle": True,
                "size": "small",
                "spacing": "large",
            },
        ]
        card = self._build_adaptive_card(body)
        return self._post(card)

    def send_alert(self, title: str, message: str, severity: str = "info") -> bool:
        theme = SEVERITY_THEMES.get(severity, SEVERITY_THEMES["info"])
        body = [
            {
                "type": "TextBlock",
                "text": title,
                "weight": "bolder",
                "size": "large",
                "color": theme["color"],
            },
            {
                "type": "TextBlock",
                "text": message,
                "wrap": True,
            },
            {
                "type": "TextBlock",
                "text": f"Severity: {severity}",
                "isSubtle": True,
                "size": "small",
            },
        ]
        card = self._build_adaptive_card(body)
        if "msteams" not in card:
            card["msteams"] = {}
        card["msteams"]["color"] = theme["accent"]
        return self._post(card)

    def _build_adaptive_card(self, body: list, actions: list = None) -> dict:
        card = {
            "type": "message",
            "attachments": [
                {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": None,
                    "content": {
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                        "type": "AdaptiveCard",
                        "version": "1.2",
                        "body": body,
                    },
                }
            ],
        }
        if actions:
            card["attachments"][0]["content"]["actions"] = actions
        return card
